connector:
    agentId: ""
    appName: ""
    appType: ""
    controllerAddr: 0.0.0.0:8099
    controllerCertFile: ""
    controllerKeyFile: ""
    natsAckWait: 30
    natsMaxInflight: 2147483647
    natsFilestoreDir: nats/datastore
    natsStoreType: FILE
    natsHost: :4222
    logFile: ""
    logLevel: 0
    enabled: false
dsConnection:
    hostName: ""
gwConnections: []
