version: "2"
run:
    go: "1.24"
    build-tags:
        - codeanalysis
linters:
    enable:
        - bodyclose
        - dogsled
        - dupl
        - goconst
        - misspell
        - prealloc
        - staticcheck
        - unconvert
        - whitespace
    disable:
        - depguard
        - funlen
        - gochecknoglobals
        - gochecknoinits
        - godox
        - gosec
        - lll
        - nakedret
        - wsl
    exclusions:
        generated: lax
        presets:
            - comments
            - common-false-positives
            - legacy
            - std-error-handling
        rules:
            - linters:
                  - dupl
                  - funlen
                  - gocognit
                  - mnd
                  - scopelint
              path: _test\.go
            - linters:
                  - dupl
                  - goconst
                  - govet
              path: _tst\.go
            - path: (.+)\.go$
              text: not declared by package utf8
            - path: (.+)\.go$
              text: unicode/utf8/utf8.go
            - path: (.+)\.go$
              text: DecodeRuneInString not declared by package utf8
            - path: (.+)\.go$
              text: .*and that stutters.*
        paths:
            - \.pb\.go$
            - connector/nsca/nsca/nsca.go
            - vendor
            - bin
            - var
            - tmp
            - gotocjson
            - libtransit
            - deprecated
            - connectors/nsca
            - connector/nsca/nsca
            - third_party$
            - builtin$
            - examples$
formatters:
    enable:
        - gofmt
        - goimports
    exclusions:
        generated: lax
        paths:
            - \.pb\.go$
            - connector/nsca/nsca/nsca.go
            - vendor
            - bin
            - var
            - tmp
            - gotocjson
            - libtransit
            - deprecated
            - connectors/nsca
            - connector/nsca/nsca
            - third_party$
            - builtin$
            - examples$
