agentConfig:
  port: 8081
  ssl: False
  startNATS: True
  startTransport: True
  startController: True
groundworkConfig:
  host: "localhost:80"
  account: "RESTAPIACCESS"
  password: "63c5BtYDNAPANvNqAkh9quYszwVrvLaruxmzvM4P1FSw"
groundworkActions:
  connect:
    entrypoint: "/api/auth/login"
  disconnect:
    entrypoint: "/api/auth/logout"
  synchronizeInventory:
    entrypoint: "/api/synchronizer"
  sendResourceWithMetrics:
    entrypoint: "/api/monitoring"
  validateToken:
    entrypoint: "/api/auth/validatetoken"
