agentConfig:
  controllerAddr: ":8081"
  natsAckWait: 15
  natsFilestoreDir: "src/main/resources/datastore"
  natsStoreType: "FILE"
  natsHost: ":4222"
  startNats: True
  startTransport: True
  startController: True
  logLevel: 1
gwConfigs:
  -
    host: "localhost:80"
    account: "RESTAPIACCESS"
    password: "6d2Ygwsw6dM8abSiGCaFvTyWXT8JP8XmuvwX4yynt5TH"
    appName: "tng"
  -
    host: "localhost:88"
    account: "RESTAPIACCESS"
    password: "6d2Ygwsw6dM8abSiGCaFvTyWXT8JP8XmuvwX4yynt5TH"
    appName: "tng"
