connector:
  agentId: ""
  appName: "ELASTIC"
  appType: "ELASTIC"
  controllerAddr: "0.0.0.0:8099"
  natsAckWait: 30
  natsMaxInflight: 2147483647 # math.MaxInt32
  natsFilestoreDir: "nats/datastore"
  natsStoreType: "FILE"
  logConsPeriod: 0 # seconds; 0 - off consolidation
  logLevel: 2
dsConnection:
  hostName: ""