agentConfig:
  controllerAddr: ":8081"
  natsAckWait: 15
  natsFilestoreDir: "src/main/resources/datastore"
  natsStoreType: "FILE"
  natsURL: "nats://localhost:4222"
  startNats: True
  startTransport: True
  startController: True
gwConfig:
  host: "localhost:80"
  account: "RESTAPIACCESS"
  password: "63c5BtYDNAPANvNqAkh9quYszwVrvLaruxmzvM4P1FSw"
  appName: "gw8"
