agentConfig:
  port: 8081
  ssl: False
  startNATS: True
  startTransport: True
  startController: False
groundworkConfig:
  host: "localhost:80"
  account: "RESTAPIACCESS"
  password: "6d2Ygwsw6dM8abSiGCaFvTyWXT8JP8XmuvwX4yynt5TH"
groundworkActions:
  connect:
    entrypoint: "/api/auth/login"
  disconnect:
    entrypoint: "/api/auth/logout"
  synchronizeInventory:
    entrypoint: "/api/synchronizer"
  sendResourceWithMetrics:
    entrypoint: "/api/monitoring"
  identity:
    entrypoint: "/api/auth/validatetoken"
