// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config": {
            "post": {
                "description": "The following API endpoint can be used to Agent configure.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent",
                    "connector"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/downtime-clear": {
            "post": {
                "description": "The following API endpoint can be used to send Downtimes to Foundation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "downtimes"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/downtime-set": {
            "post": {
                "description": "The following API endpoint can be used to send Downtimes to Foundation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "downtimes"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events": {
            "post": {
                "description": "The following API endpoint can be used to send Alerts to Foundation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alert",
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events-ack": {
            "post": {
                "description": "The following API endpoint can be used to send Alerts to Foundation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alert",
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events-unack": {
            "post": {
                "description": "The following API endpoint can be used to send Alerts to Foundation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alert",
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/identity": {
            "get": {
                "description": "The following API endpoint can be used to get a TCG agent id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent",
                    "connector"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gwos_tcg_sdk_transit.AgentIdentity"
                        }
                    }
                }
            }
        },
        "/inventory": {
            "post": {
                "description": "The following API endpoint can be used to send Inventory to Foundation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "The following API endpoint can be used to get list of metrics from the server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metric"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "The following API endpoint can be used to send Metrics to Foundation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/reset-nats": {
            "post": {
                "description": "The following API endpoint can be used to reset NATS queues.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent",
                    "connector"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ConnectorStatusDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/start": {
            "post": {
                "description": "The following API endpoint can be used to start NATS dispatcher.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent",
                    "connector"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ConnectorStatusDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "The following API endpoint can be used to get TCG statistics.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent",
                    "connector"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "gwos-app-name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.AgentStatsExt"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "The following API endpoint can be used to get TCG status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent",
                    "connector"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ConnectorStatusDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stop": {
            "post": {
                "description": "The following API endpoint can be used to stop NATS dispatcher.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent",
                    "connector"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ConnectorStatusDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "The following API endpoint can be used to return actual TCG connector version.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent",
                    "connector"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config.BuildInfo"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.BuildInfo": {
            "type": "object",
            "properties": {
                "tag": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "expvar.Int": {
            "type": "object"
        },
        "github_com_gwos_tcg_sdk_transit.AgentIdentity": {
            "type": "object",
            "properties": {
                "agentId": {
                    "type": "string"
                },
                "appName": {
                    "type": "string"
                },
                "appType": {
                    "type": "string"
                }
            }
        },
        "logzer.LogRecord": {
            "type": "object"
        },
        "services.AgentStatsExt": {
            "type": "object",
            "properties": {
                "agentId": {
                    "type": "string"
                },
                "appName": {
                    "type": "string"
                },
                "appType": {
                    "type": "string"
                },
                "bytesSent": {
                    "$ref": "#/definitions/expvar.Int"
                },
                "executionTimeInventory": {
                    "$ref": "#/definitions/expvar.Int"
                },
                "executionTimeMetrics": {
                    "$ref": "#/definitions/expvar.Int"
                },
                "lastErrors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/logzer.LogRecord"
                    }
                },
                "lastEventsRun": {
                    "$ref": "#/definitions/expvar.Int"
                },
                "lastInventoryRun": {
                    "$ref": "#/definitions/expvar.Int"
                },
                "lastMetricsRun": {
                    "$ref": "#/definitions/expvar.Int"
                },
                "messagesSent": {
                    "$ref": "#/definitions/expvar.Int"
                },
                "metricsSent": {
                    "$ref": "#/definitions/expvar.Int"
                },
                "upSince": {
                    "$ref": "#/definitions/expvar.Int"
                }
            }
        },
        "services.ConnectorStatusDTO": {
            "type": "object",
            "properties": {
                "connectorStatus": {
                    "type": "string"
                },
                "jobId": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
