// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-12-27 14:50:07.372153953 +0300 +03 m=+0.151298301

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/listMetrics": {
            "get": {
                "description": "The following API endpoint can be used to get list of metrics from the server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.AgentStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/nats": {
            "post": {
                "description": "The following API endpoint can be used to start NATS streaming server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NATS"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.AgentStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "The following API endpoint can be used to stop NATS streaming server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NATS"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.AgentStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/nats/transport": {
            "post": {
                "description": "The following API endpoint can be used to start NATS transport(this means that messages will begin to be sent).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NATS"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.AgentStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "The following API endpoint can be used to stop NATS transport.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NATS"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.AgentStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "The following API endpoint can be used to get TNG statistics.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "gwos-app-name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "gwos-api-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.AgentStats"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "The following API endpoint can be used to get TNG status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-APP-NAME",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Auth header",
                        "name": "GWOS-API-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.AgentStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "services.AgentStats": {
            "type": "object",
            "properties": {
                "agentID": {
                    "type": "string"
                },
                "appType": {
                    "type": "string"
                },
                "bytesSent": {
                    "type": "integer"
                },
                "executionTimeInventory": {
                    "type": "string"
                },
                "executionTimeMetrics": {
                    "type": "string"
                },
                "lastError": {
                    "type": "string"
                },
                "lastInventoryRun": {
                    "type": "object",
                    "$ref": "#/definitions/subseconds.MillisecondTimestamp"
                },
                "lastMetricsRun": {
                    "type": "object",
                    "$ref": "#/definitions/subseconds.MillisecondTimestamp"
                },
                "messagesSent": {
                    "type": "integer"
                },
                "metricsSent": {
                    "type": "integer"
                },
                "upSince": {
                    "type": "object",
                    "$ref": "#/definitions/subseconds.MillisecondTimestamp"
                }
            }
        },
        "services.AgentStatus": {
            "type": "object",
            "properties": {
                "controller": {
                    "type": "string"
                },
                "nats": {
                    "type": "string"
                },
                "transport": {
                    "type": "string"
                }
            }
        },
        "subseconds.MillisecondTimestamp": {
            "type": "object"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8081",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "TNG API Documentation",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
