basePath: /api/v1
definitions:
  services.AgentStats:
    properties:
      agentID:
        type: string
      appType:
        type: string
      bytesSent:
        type: integer
      executionTimeInventory:
        type: string
      executionTimeMetrics:
        type: string
      lastError:
        type: string
      lastInventoryRun:
        $ref: '#/definitions/subseconds.MillisecondTimestamp'
        type: object
      lastMetricsRun:
        $ref: '#/definitions/subseconds.MillisecondTimestamp'
        type: object
      messagesSent:
        type: integer
      metricsSent:
        type: integer
      upSince:
        $ref: '#/definitions/subseconds.MillisecondTimestamp'
        type: object
    type: object
  services.AgentStatus:
    properties:
      controller:
        type: string
      nats:
        type: string
      transport:
        type: string
    type: object
  setup.GWConnection:
    properties:
      hostName:
        description: |-
          HostName accepts value for combined "host:port"
          used as `url.URL{HostName}`
        type: string
      password:
        type: string
      userName:
        type: string
    type: object
  setup.GWConnections:
    items:
      $ref: '#/definitions/setup.GWConnection'
    type: array
  subseconds.MillisecondTimestamp:
    type: object
host: localhost:8081
info:
  contact: {}
  license: {}
  title: TNG API Documentation
  version: "1.0"
paths:
  /gw-connections:
    get:
      consumes:
      - application/json
      description: The following API endpoint can be used to get list of GroundworkConnections
        from the server.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setup.GWConnections'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - Metrics
    post:
      consumes:
      - application/json
      description: The following API endpoint can be used to update list of GroundworkConnections
        from the server.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setup.GWConnections'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - Metrics
  /metrics:
    get:
      consumes:
      - application/json
      description: The following API endpoint can be used to get list of metrics from
        the server.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AgentStatus'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - Metrics
  /nats:
    delete:
      consumes:
      - application/json
      description: The following API endpoint can be used to stop NATS streaming server.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AgentStatus'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - NATS
    post:
      consumes:
      - application/json
      description: The following API endpoint can be used to start NATS streaming
        server.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AgentStatus'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - NATS
  /nats/transport:
    delete:
      consumes:
      - application/json
      description: The following API endpoint can be used to stop NATS transport.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AgentStatus'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - NATS
    post:
      consumes:
      - application/json
      description: The following API endpoint can be used to start NATS transport(this
        means that messages will begin to be sent).
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AgentStatus'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - NATS
  /stats:
    get:
      consumes:
      - application/json
      description: The following API endpoint can be used to get TNG statistics.
      parameters:
      - description: Auth header
        in: header
        name: gwos-app-name
        required: true
        type: string
      - description: Auth header
        in: header
        name: gwos-api-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AgentStats'
        "401":
          description: Unauthorized
          schema:
            type: string
      tags:
      - Agent
  /status:
    get:
      consumes:
      - application/json
      description: The following API endpoint can be used to get TNG status.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AgentStatus'
        "401":
          description: Unauthorized
          schema:
            type: string
      tags:
      - Server
swagger: "2.0"
