definitions:
  milliseconds.MillisecondTimestamp:
    type: object
  services.AgentIdentity:
    properties:
      agentID:
        type: string
      appName:
        type: string
      appType:
        type: string
    type: object
  services.AgentIdentityStats:
    properties:
      agentID:
        type: string
      appName:
        type: string
      appType:
        type: string
      bytesSent:
        type: integer
      executionTimeInventory:
        type: string
      executionTimeMetrics:
        type: string
      lastAlertRun:
        $ref: '#/definitions/milliseconds.MillisecondTimestamp'
        type: object
      lastErrors:
        items:
          $ref: '#/definitions/services.LastError'
        type: array
      lastInventoryRun:
        $ref: '#/definitions/milliseconds.MillisecondTimestamp'
        type: object
      lastMetricsRun:
        $ref: '#/definitions/milliseconds.MillisecondTimestamp'
        type: object
      messagesSent:
        type: integer
      metricsSent:
        type: integer
      upSince:
        $ref: '#/definitions/milliseconds.MillisecondTimestamp'
        type: object
    type: object
  services.AgentStatus:
    properties:
      controller:
        type: string
      ctrl:
        $ref: '#/definitions/services.CtrlAction'
        type: object
      nats:
        type: string
      transport:
        type: string
    type: object
  services.ConnectorStatusDTO:
    properties:
      connectorStatus:
        type: string
      jobId:
        type: integer
    type: object
  services.LastError:
    properties:
      message:
        type: string
      time:
        $ref: '#/definitions/milliseconds.MillisecondTimestamp'
        type: object
    type: object
info:
  contact: {}
  license: {}
paths:
  /agent:
    get:
      consumes:
      - application/json
      description: The following API endpoint can be used to get a TCG agent id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AgentIdentity'
      tags:
      - agent
      - connector
  /config:
    post:
      consumes:
      - application/json
      description: The following API endpoint can be used to Agent configure.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
        "401":
          description: Unauthorized
          schema:
            type: string
      tags:
      - agent
      - connector
  /events:
    post:
      consumes:
      - application/json
      description: The following API endpoint can be used to send Alerts to Foundation.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
        "401":
          description: Unauthorized
          schema:
            type: string
      tags:
      - alert
      - event
  /events-ack:
    post:
      consumes:
      - application/json
      description: The following API endpoint can be used to send Alerts to Foundation.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
        "401":
          description: Unauthorized
          schema:
            type: string
      tags:
      - alert
      - event
  /events-unack:
    post:
      consumes:
      - application/json
      description: The following API endpoint can be used to send Alerts to Foundation.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
        "401":
          description: Unauthorized
          schema:
            type: string
      tags:
      - alert
      - event
  /metrics:
    get:
      consumes:
      - application/json
      description: The following API endpoint can be used to get list of metrics from
        the server.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AgentStatus'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - metric
  /start:
    post:
      consumes:
      - application/json
      description: The following API endpoint can be used to start NATS dispatcher.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ConnectorStatusDTO'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - agent
      - connector
  /stats:
    get:
      consumes:
      - application/json
      description: The following API endpoint can be used to get TCG statistics.
      parameters:
      - description: Auth header
        in: header
        name: gwos-app-name
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AgentIdentityStats'
        "401":
          description: Unauthorized
          schema:
            type: string
      tags:
      - agent
      - connector
  /status:
    get:
      consumes:
      - application/json
      description: The following API endpoint can be used to get TCG status.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ConnectorStatusDTO'
        "401":
          description: Unauthorized
          schema:
            type: string
      tags:
      - agent
      - connector
  /stop:
    post:
      consumes:
      - application/json
      description: The following API endpoint can be used to stop NATS dispatcher.
      parameters:
      - description: Auth header
        in: header
        name: GWOS-APP-NAME
        required: true
        type: string
      - description: Auth header
        in: header
        name: GWOS-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ConnectorStatusDTO'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - agent
      - connector
swagger: "2.0"
